app:
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

scrapper:
  url: ${SCRAPPER_URL:http://localhost:8080}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
