app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080

scrapper:
  url: ${SCRAPPER_URL:http://localhost:8081}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
